name: Build and Test

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ['7.0.406']
        node-version: ['21.5']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        dotnet build
        cd ./client
        npm install --legacy-peer-deps

    - name: Build and Start Server
      run: |
        dotnet watch -p ./API &
        npm start --prefix ./client &
        wait
